/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthSubscriptionTiers200ResponseTiers } from './AuthSubscriptionTiers200ResponseTiers';
import {
    AuthSubscriptionTiers200ResponseTiersFromJSON,
    AuthSubscriptionTiers200ResponseTiersFromJSONTyped,
    AuthSubscriptionTiers200ResponseTiersToJSON,
} from './AuthSubscriptionTiers200ResponseTiers';

/**
 * 
 * @export
 * @interface AuthSubscriptionTiers200Response
 */
export interface AuthSubscriptionTiers200Response {
    /**
     * 
     * @type {AuthSubscriptionTiers200ResponseTiers}
     * @memberof AuthSubscriptionTiers200Response
     */
    tiers?: AuthSubscriptionTiers200ResponseTiers;
}

/**
 * Check if a given object implements the AuthSubscriptionTiers200Response interface.
 */
export function instanceOfAuthSubscriptionTiers200Response(value: object): value is AuthSubscriptionTiers200Response {
    return true;
}

export function AuthSubscriptionTiers200ResponseFromJSON(json: any): AuthSubscriptionTiers200Response {
    return AuthSubscriptionTiers200ResponseFromJSONTyped(json, false);
}

export function AuthSubscriptionTiers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSubscriptionTiers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tiers': json['tiers'] == null ? undefined : AuthSubscriptionTiers200ResponseTiersFromJSON(json['tiers']),
    };
}

export function AuthSubscriptionTiers200ResponseToJSON(value?: AuthSubscriptionTiers200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tiers': AuthSubscriptionTiers200ResponseTiersToJSON(value['tiers']),
    };
}

