/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCreateSubscription400Response
 */
export interface AuthCreateSubscription400Response {
    /**
     * 
     * @type {string}
     * @memberof AuthCreateSubscription400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the AuthCreateSubscription400Response interface.
 */
export function instanceOfAuthCreateSubscription400Response(value: object): value is AuthCreateSubscription400Response {
    return true;
}

export function AuthCreateSubscription400ResponseFromJSON(json: any): AuthCreateSubscription400Response {
    return AuthCreateSubscription400ResponseFromJSONTyped(json, false);
}

export function AuthCreateSubscription400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCreateSubscription400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AuthCreateSubscription400ResponseToJSON(value?: AuthCreateSubscription400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

