/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCreateSubscription200Response
 */
export interface AuthCreateSubscription200Response {
    /**
     * Stripe checkout session ID
     * @type {string}
     * @memberof AuthCreateSubscription200Response
     */
    sessionId?: string;
    /**
     * URL to redirect user to Stripe checkout
     * @type {string}
     * @memberof AuthCreateSubscription200Response
     */
    checkoutUrl?: string;
}

/**
 * Check if a given object implements the AuthCreateSubscription200Response interface.
 */
export function instanceOfAuthCreateSubscription200Response(value: object): value is AuthCreateSubscription200Response {
    return true;
}

export function AuthCreateSubscription200ResponseFromJSON(json: any): AuthCreateSubscription200Response {
    return AuthCreateSubscription200ResponseFromJSONTyped(json, false);
}

export function AuthCreateSubscription200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCreateSubscription200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
        'checkoutUrl': json['checkout_url'] == null ? undefined : json['checkout_url'],
    };
}

export function AuthCreateSubscription200ResponseToJSON(value?: AuthCreateSubscription200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
        'checkout_url': value['checkoutUrl'],
    };
}

