/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResult
 */
export interface BaseResult {
    /**
     * 
     * @type {Date}
     * @memberof BaseResult
     */
    scheduleDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BaseResult
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the BaseResult interface.
 */
export function instanceOfBaseResult(value: object): value is BaseResult {
    if (!('scheduleDate' in value) || value['scheduleDate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BaseResultFromJSON(json: any): BaseResult {
    return BaseResultFromJSONTyped(json, false);
}

export function BaseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleDate': (json['schedule_date'] == null ? null : new Date(json['schedule_date'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BaseResultToJSON(value?: Omit<BaseResult, 'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schedule_date': (value['scheduleDate'] == null ? null : (value['scheduleDate'] as any).toISOString()),
    };
}

