/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';

/**
 * 
 * @export
 * @interface BaseFieldsCreate
 */
export interface BaseFieldsCreate {
    /**
     * 
     * @type {string}
     * @memberof BaseFieldsCreate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseFieldsCreate
     */
    description?: string;
    /**
     * 
     * @type {Array<DrawMetadata>}
     * @memberof BaseFieldsCreate
     */
    metadata?: Array<DrawMetadata>;
}

/**
 * Check if a given object implements the BaseFieldsCreate interface.
 */
export function instanceOfBaseFieldsCreate(value: object): value is BaseFieldsCreate {
    return true;
}

export function BaseFieldsCreateFromJSON(json: any): BaseFieldsCreate {
    return BaseFieldsCreateFromJSONTyped(json, false);
}

export function BaseFieldsCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseFieldsCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : ((json['metadata'] as Array<any>).map(DrawMetadataFromJSON)),
    };
}

export function BaseFieldsCreateToJSON(value?: BaseFieldsCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'metadata': value['metadata'] == null ? undefined : ((value['metadata'] as Array<any>).map(DrawMetadataToJSON)),
    };
}

