/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSecretSantaPayloadParticipantsInner
 */
export interface CreateSecretSantaPayloadParticipantsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateSecretSantaPayloadParticipantsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSecretSantaPayloadParticipantsInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSecretSantaPayloadParticipantsInner
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSecretSantaPayloadParticipantsInner
     */
    exclusions: Array<string>;
}

/**
 * Check if a given object implements the CreateSecretSantaPayloadParticipantsInner interface.
 */
export function instanceOfCreateSecretSantaPayloadParticipantsInner(value: object): value is CreateSecretSantaPayloadParticipantsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('exclusions' in value) || value['exclusions'] === undefined) return false;
    return true;
}

export function CreateSecretSantaPayloadParticipantsInnerFromJSON(json: any): CreateSecretSantaPayloadParticipantsInner {
    return CreateSecretSantaPayloadParticipantsInnerFromJSONTyped(json, false);
}

export function CreateSecretSantaPayloadParticipantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSecretSantaPayloadParticipantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'exclusions': json['exclusions'],
    };
}

export function CreateSecretSantaPayloadParticipantsInnerToJSON(value?: CreateSecretSantaPayloadParticipantsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'exclusions': value['exclusions'],
    };
}

