/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseFieldsCreate } from './BaseFieldsCreate';
import {
    BaseFieldsCreateFromJSON,
    BaseFieldsCreateFromJSONTyped,
    BaseFieldsCreateToJSON,
} from './BaseFieldsCreate';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { PrizeField } from './PrizeField';
import {
    PrizeFieldFromJSON,
    PrizeFieldFromJSONTyped,
    PrizeFieldToJSON,
} from './PrizeField';

/**
 * 
 * @export
 * @interface CreateTiktokPayload
 */
export interface CreateTiktokPayload extends BaseFieldsCreate {
    /**
     * 
     * @type {Array<PrizeField>}
     * @memberof CreateTiktokPayload
     */
    prizes: Array<PrizeField>;
    /**
     * 
     * @type {number}
     * @memberof CreateTiktokPayload
     */
    minMentions: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTiktokPayload
     */
    postUrl: string;
}

/**
 * Check if a given object implements the CreateTiktokPayload interface.
 */
export function instanceOfCreateTiktokPayload(value: object): value is CreateTiktokPayload {
    if (!('prizes' in value) || value['prizes'] === undefined) return false;
    if (!('minMentions' in value) || value['minMentions'] === undefined) return false;
    if (!('postUrl' in value) || value['postUrl'] === undefined) return false;
    return true;
}

export function CreateTiktokPayloadFromJSON(json: any): CreateTiktokPayload {
    return CreateTiktokPayloadFromJSONTyped(json, false);
}

export function CreateTiktokPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTiktokPayload {
    if (json == null) {
        return json;
    }
    return {
        ...BaseFieldsCreateFromJSONTyped(json, ignoreDiscriminator),
        'prizes': ((json['prizes'] as Array<any>).map(PrizeFieldFromJSON)),
        'minMentions': json['min_mentions'],
        'postUrl': json['post_url'],
    };
}

export function CreateTiktokPayloadToJSON(value?: CreateTiktokPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseFieldsCreateToJSON(value),
        'prizes': ((value['prizes'] as Array<any>).map(PrizeFieldToJSON)),
        'min_mentions': value['minMentions'],
        'post_url': value['postUrl'],
    };
}

