/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSecretSantaPayloadParticipantsInner } from './CreateSecretSantaPayloadParticipantsInner';
import {
    CreateSecretSantaPayloadParticipantsInnerFromJSON,
    CreateSecretSantaPayloadParticipantsInnerFromJSONTyped,
    CreateSecretSantaPayloadParticipantsInnerToJSON,
} from './CreateSecretSantaPayloadParticipantsInner';

/**
 * 
 * @export
 * @interface CreateSecretSantaPayload
 */
export interface CreateSecretSantaPayload {
    /**
     * 
     * @type {string}
     * @memberof CreateSecretSantaPayload
     */
    language: CreateSecretSantaPayloadLanguageEnum;
    /**
     * 
     * @type {Array<CreateSecretSantaPayloadParticipantsInner>}
     * @memberof CreateSecretSantaPayload
     */
    participants: Array<CreateSecretSantaPayloadParticipantsInner>;
}


/**
 * @export
 */
export const CreateSecretSantaPayloadLanguageEnum = {
    Es: 'es',
    En: 'en'
} as const;
export type CreateSecretSantaPayloadLanguageEnum = typeof CreateSecretSantaPayloadLanguageEnum[keyof typeof CreateSecretSantaPayloadLanguageEnum];


/**
 * Check if a given object implements the CreateSecretSantaPayload interface.
 */
export function instanceOfCreateSecretSantaPayload(value: object): value is CreateSecretSantaPayload {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function CreateSecretSantaPayloadFromJSON(json: any): CreateSecretSantaPayload {
    return CreateSecretSantaPayloadFromJSONTyped(json, false);
}

export function CreateSecretSantaPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSecretSantaPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'participants': ((json['participants'] as Array<any>).map(CreateSecretSantaPayloadParticipantsInnerFromJSON)),
    };
}

export function CreateSecretSantaPayloadToJSON(value?: CreateSecretSantaPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'language': value['language'],
        'participants': ((value['participants'] as Array<any>).map(CreateSecretSantaPayloadParticipantsInnerToJSON)),
    };
}

