/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { BaseFields } from './BaseFields';
import {
    BaseFieldsFromJSON,
    BaseFieldsFromJSONTyped,
    BaseFieldsToJSON,
} from './BaseFields';

/**
 * 
 * @export
 * @interface CreateLinkPayload
 */
export interface CreateLinkPayload extends BaseFields {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateLinkPayload
     */
    itemsSet1: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateLinkPayload
     */
    itemsSet2: Array<string>;
}



/**
 * Check if a given object implements the CreateLinkPayload interface.
 */
export function instanceOfCreateLinkPayload(value: object): value is CreateLinkPayload {
    if (!('itemsSet1' in value) || value['itemsSet1'] === undefined) return false;
    if (!('itemsSet2' in value) || value['itemsSet2'] === undefined) return false;
    return true;
}

export function CreateLinkPayloadFromJSON(json: any): CreateLinkPayload {
    return CreateLinkPayloadFromJSONTyped(json, false);
}

export function CreateLinkPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLinkPayload {
    if (json == null) {
        return json;
    }
    return {
        ...BaseFieldsFromJSONTyped(json, ignoreDiscriminator),
        'itemsSet1': json['items_set1'],
        'itemsSet2': json['items_set2'],
    };
}

export function CreateLinkPayloadToJSON(value?: CreateLinkPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseFieldsToJSON(value),
        'items_set1': value['itemsSet1'],
        'items_set2': value['itemsSet2'],
    };
}

