/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrawReTossPayload
 */
export interface DrawReTossPayload {
    /**
     * 
     * @type {string}
     * @memberof DrawReTossPayload
     */
    prizeId?: string;
}

/**
 * Check if a given object implements the DrawReTossPayload interface.
 */
export function instanceOfDrawReTossPayload(value: object): value is DrawReTossPayload {
    return true;
}

export function DrawReTossPayloadFromJSON(json: any): DrawReTossPayload {
    return DrawReTossPayloadFromJSONTyped(json, false);
}

export function DrawReTossPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawReTossPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'prizeId': json['prize_id'] == null ? undefined : json['prize_id'],
    };
}

export function DrawReTossPayloadToJSON(value?: DrawReTossPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'prize_id': value['prizeId'],
    };
}

