/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrawTossPayload
 */
export interface DrawTossPayload {
    /**
     * 
     * @type {Date}
     * @memberof DrawTossPayload
     */
    scheduleDate?: Date;
}

/**
 * Check if a given object implements the DrawTossPayload interface.
 */
export function instanceOfDrawTossPayload(value: object): value is DrawTossPayload {
    return true;
}

export function DrawTossPayloadFromJSON(json: any): DrawTossPayload {
    return DrawTossPayloadFromJSONTyped(json, false);
}

export function DrawTossPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawTossPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleDate': json['schedule_date'] == null ? undefined : (new Date(json['schedule_date'])),
    };
}

export function DrawTossPayloadToJSON(value?: DrawTossPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schedule_date': value['scheduleDate'] == null ? undefined : ((value['scheduleDate']).toISOString()),
    };
}

