/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramPreviewRequest
 */
export interface InstagramPreviewRequest {
    /**
     * 
     * @type {string}
     * @memberof InstagramPreviewRequest
     */
    url: string;
}

/**
 * Check if a given object implements the InstagramPreviewRequest interface.
 */
export function instanceOfInstagramPreviewRequest(value: object): value is InstagramPreviewRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function InstagramPreviewRequestFromJSON(json: any): InstagramPreviewRequest {
    return InstagramPreviewRequestFromJSONTyped(json, false);
}

export function InstagramPreviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramPreviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function InstagramPreviewRequestToJSON(value?: InstagramPreviewRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

