/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { BaseDraw } from './BaseDraw';
import {
    BaseDrawFromJSON,
    BaseDrawFromJSONTyped,
    BaseDrawToJSON,
} from './BaseDraw';
import type { InstagramResult } from './InstagramResult';
import {
    InstagramResultFromJSON,
    InstagramResultFromJSONTyped,
    InstagramResultToJSON,
} from './InstagramResult';
import type { PrizeField } from './PrizeField';
import {
    PrizeFieldFromJSON,
    PrizeFieldFromJSONTyped,
    PrizeFieldToJSON,
} from './PrizeField';

/**
 * 
 * @export
 * @interface Instagram
 */
export interface Instagram extends BaseDraw {
    /**
     * 
     * @type {Array<PrizeField>}
     * @memberof Instagram
     */
    prizes: Array<PrizeField>;
    /**
     * 
     * @type {boolean}
     * @memberof Instagram
     */
    useLikes: boolean;
    /**
     * 
     * @type {number}
     * @memberof Instagram
     */
    minMentions: number;
    /**
     * 
     * @type {string}
     * @memberof Instagram
     */
    postUrl: string;
    /**
     * 
     * @type {Array<InstagramResult>}
     * @memberof Instagram
     */
    readonly results: Array<InstagramResult>;
}



/**
 * Check if a given object implements the Instagram interface.
 */
export function instanceOfInstagram(value: object): value is Instagram {
    if (!('prizes' in value) || value['prizes'] === undefined) return false;
    if (!('useLikes' in value) || value['useLikes'] === undefined) return false;
    if (!('minMentions' in value) || value['minMentions'] === undefined) return false;
    if (!('postUrl' in value) || value['postUrl'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function InstagramFromJSON(json: any): Instagram {
    return InstagramFromJSONTyped(json, false);
}

export function InstagramFromJSONTyped(json: any, ignoreDiscriminator: boolean): Instagram {
    if (json == null) {
        return json;
    }
    return {
        ...BaseDrawFromJSONTyped(json, ignoreDiscriminator),
        'prizes': ((json['prizes'] as Array<any>).map(PrizeFieldFromJSON)),
        'useLikes': json['use_likes'],
        'minMentions': json['min_mentions'],
        'postUrl': json['post_url'],
        'results': ((json['results'] as Array<any>).map(InstagramResultFromJSON)),
    };
}

export function InstagramToJSON(value?: Omit<Instagram, 'results'|'id'|'created_at'|'updated_at'|'private_id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseDrawToJSON(value),
        'prizes': ((value['prizes'] as Array<any>).map(PrizeFieldToJSON)),
        'use_likes': value['useLikes'],
        'min_mentions': value['minMentions'],
        'post_url': value['postUrl'],
    };
}

