/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramPreview
 */
export interface InstagramPreview {
    /**
     * 
     * @type {string}
     * @memberof InstagramPreview
     */
    postPic: string;
    /**
     * 
     * @type {number}
     * @memberof InstagramPreview
     */
    commentCount: number;
    /**
     * 
     * @type {string}
     * @memberof InstagramPreview
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramPreview
     */
    userPic: string;
}

/**
 * Check if a given object implements the InstagramPreview interface.
 */
export function instanceOfInstagramPreview(value: object): value is InstagramPreview {
    if (!('postPic' in value) || value['postPic'] === undefined) return false;
    if (!('commentCount' in value) || value['commentCount'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userPic' in value) || value['userPic'] === undefined) return false;
    return true;
}

export function InstagramPreviewFromJSON(json: any): InstagramPreview {
    return InstagramPreviewFromJSONTyped(json, false);
}

export function InstagramPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'postPic': json['post_pic'],
        'commentCount': json['comment_count'],
        'userName': json['user_name'],
        'userPic': json['user_pic'],
    };
}

export function InstagramPreviewToJSON(value?: InstagramPreview | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'post_pic': value['postPic'],
        'comment_count': value['commentCount'],
        'user_name': value['userName'],
        'user_pic': value['userPic'],
    };
}

