/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParticipantField } from './ParticipantField';
import {
    ParticipantFieldFromJSON,
    ParticipantFieldFromJSONTyped,
    ParticipantFieldToJSON,
} from './ParticipantField';

/**
 * 
 * @export
 * @interface LotteryFields
 */
export interface LotteryFields {
    /**
     * 
     * @type {Array<ParticipantField>}
     * @memberof LotteryFields
     */
    participants: Array<ParticipantField>;
    /**
     * 
     * @type {number}
     * @memberof LotteryFields
     */
    numberOfResults?: number;
}

/**
 * Check if a given object implements the LotteryFields interface.
 */
export function instanceOfLotteryFields(value: object): value is LotteryFields {
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function LotteryFieldsFromJSON(json: any): LotteryFields {
    return LotteryFieldsFromJSONTyped(json, false);
}

export function LotteryFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryFields {
    if (json == null) {
        return json;
    }
    return {
        
        'participants': ((json['participants'] as Array<any>).map(ParticipantFieldFromJSON)),
        'numberOfResults': json['number_of_results'] == null ? undefined : json['number_of_results'],
    };
}

export function LotteryFieldsToJSON(value?: LotteryFields | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'participants': ((value['participants'] as Array<any>).map(ParticipantFieldToJSON)),
        'number_of_results': value['numberOfResults'],
    };
}

