/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaypalCreatePayload
 */
export interface PaypalCreatePayload {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaypalCreatePayload
     */
    options: Array<PaypalCreatePayloadOptionsEnum>;
    /**
     * 
     * @type {string}
     * @memberof PaypalCreatePayload
     */
    drawUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PaypalCreatePayload
     */
    drawId: string;
}


/**
 * @export
 */
export const PaypalCreatePayloadOptionsEnum = {
    Certified: 'CERTIFIED',
    Adfree: 'ADFREE',
    Support: 'SUPPORT'
} as const;
export type PaypalCreatePayloadOptionsEnum = typeof PaypalCreatePayloadOptionsEnum[keyof typeof PaypalCreatePayloadOptionsEnum];


/**
 * Check if a given object implements the PaypalCreatePayload interface.
 */
export function instanceOfPaypalCreatePayload(value: object): value is PaypalCreatePayload {
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('drawUrl' in value) || value['drawUrl'] === undefined) return false;
    if (!('drawId' in value) || value['drawId'] === undefined) return false;
    return true;
}

export function PaypalCreatePayloadFromJSON(json: any): PaypalCreatePayload {
    return PaypalCreatePayloadFromJSONTyped(json, false);
}

export function PaypalCreatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaypalCreatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'],
        'drawUrl': json['draw_url'],
        'drawId': json['draw_id'],
    };
}

export function PaypalCreatePayloadToJSON(value?: PaypalCreatePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'options': value['options'],
        'draw_url': value['drawUrl'],
        'draw_id': value['drawId'],
    };
}

