/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { BaseDraw } from './BaseDraw';
import {
    BaseDrawFromJSON,
    BaseDrawFromJSONTyped,
    BaseDrawToJSON,
} from './BaseDraw';
import type { Participant } from './Participant';
import {
    ParticipantFromJSON,
    ParticipantFromJSONTyped,
    ParticipantToJSON,
} from './Participant';
import type { RaffleResult } from './RaffleResult';
import {
    RaffleResultFromJSON,
    RaffleResultFromJSONTyped,
    RaffleResultToJSON,
} from './RaffleResult';
import type { Prize } from './Prize';
import {
    PrizeFromJSON,
    PrizeFromJSONTyped,
    PrizeToJSON,
} from './Prize';

/**
 * 
 * @export
 * @interface Raffle
 */
export interface Raffle extends BaseDraw {
    /**
     * 
     * @type {Array<Prize>}
     * @memberof Raffle
     */
    prizes: Array<Prize>;
    /**
     * 
     * @type {Array<Participant>}
     * @memberof Raffle
     */
    participants: Array<Participant>;
    /**
     * 
     * @type {Array<RaffleResult>}
     * @memberof Raffle
     */
    readonly results?: Array<RaffleResult>;
}



/**
 * Check if a given object implements the Raffle interface.
 */
export function instanceOfRaffle(value: object): value is Raffle {
    if (!('prizes' in value) || value['prizes'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function RaffleFromJSON(json: any): Raffle {
    return RaffleFromJSONTyped(json, false);
}

export function RaffleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Raffle {
    if (json == null) {
        return json;
    }
    return {
        ...BaseDrawFromJSONTyped(json, ignoreDiscriminator),
        'prizes': ((json['prizes'] as Array<any>).map(PrizeFromJSON)),
        'participants': ((json['participants'] as Array<any>).map(ParticipantFromJSON)),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(RaffleResultFromJSON)),
    };
}

export function RaffleToJSON(value?: Omit<Raffle, 'results'|'id'|'created_at'|'updated_at'|'private_id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseDrawToJSON(value),
        'prizes': ((value['prizes'] as Array<any>).map(PrizeToJSON)),
        'participants': ((value['participants'] as Array<any>).map(ParticipantToJSON)),
    };
}

