/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevolutResponse
 */
export interface RevolutResponse {
    /**
     * 
     * @type {string}
     * @memberof RevolutResponse
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the RevolutResponse interface.
 */
export function instanceOfRevolutResponse(value: object): value is RevolutResponse {
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    return true;
}

export function RevolutResponseFromJSON(json: any): RevolutResponse {
    return RevolutResponseFromJSONTyped(json, false);
}

export function RevolutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevolutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirect_url'],
    };
}

export function RevolutResponseToJSON(value?: RevolutResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'redirect_url': value['redirectUrl'],
    };
}

