/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretSantaErrorResponseBody } from './SecretSantaErrorResponseBody';
import {
    SecretSantaErrorResponseBodyFromJSON,
    SecretSantaErrorResponseBodyFromJSONTyped,
    SecretSantaErrorResponseBodyToJSON,
} from './SecretSantaErrorResponseBody';

/**
 * 
 * @export
 * @interface SecretSantaErrorResponse
 */
export interface SecretSantaErrorResponse {
    /**
     * 
     * @type {SecretSantaErrorResponseBody}
     * @memberof SecretSantaErrorResponse
     */
    body?: SecretSantaErrorResponseBody;
}

/**
 * Check if a given object implements the SecretSantaErrorResponse interface.
 */
export function instanceOfSecretSantaErrorResponse(value: object): value is SecretSantaErrorResponse {
    return true;
}

export function SecretSantaErrorResponseFromJSON(json: any): SecretSantaErrorResponse {
    return SecretSantaErrorResponseFromJSONTyped(json, false);
}

export function SecretSantaErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretSantaErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : SecretSantaErrorResponseBodyFromJSON(json['body']),
    };
}

export function SecretSantaErrorResponseToJSON(value?: SecretSantaErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'body': SecretSantaErrorResponseBodyToJSON(value['body']),
    };
}

