/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { BaseDraw } from './BaseDraw';
import {
    BaseDrawFromJSON,
    BaseDrawFromJSONTyped,
    BaseDrawToJSON,
} from './BaseDraw';
import type { ShiftsResult } from './ShiftsResult';
import {
    ShiftsResultFromJSON,
    ShiftsResultFromJSONTyped,
    ShiftsResultToJSON,
} from './ShiftsResult';
import type { Participant } from './Participant';
import {
    ParticipantFromJSON,
    ParticipantFromJSONTyped,
    ParticipantToJSON,
} from './Participant';
import type { ShiftsInterval } from './ShiftsInterval';
import {
    ShiftsIntervalFromJSON,
    ShiftsIntervalFromJSONTyped,
    ShiftsIntervalToJSON,
} from './ShiftsInterval';

/**
 * 
 * @export
 * @interface Shifts
 */
export interface Shifts extends BaseDraw {
    /**
     * 
     * @type {Array<ShiftsInterval>}
     * @memberof Shifts
     */
    intervals: Array<ShiftsInterval>;
    /**
     * 
     * @type {Array<Participant>}
     * @memberof Shifts
     */
    participants: Array<Participant>;
    /**
     * 
     * @type {Array<ShiftsResult>}
     * @memberof Shifts
     */
    readonly results?: Array<ShiftsResult>;
}



/**
 * Check if a given object implements the Shifts interface.
 */
export function instanceOfShifts(value: object): value is Shifts {
    if (!('intervals' in value) || value['intervals'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function ShiftsFromJSON(json: any): Shifts {
    return ShiftsFromJSONTyped(json, false);
}

export function ShiftsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shifts {
    if (json == null) {
        return json;
    }
    return {
        ...BaseDrawFromJSONTyped(json, ignoreDiscriminator),
        'intervals': ((json['intervals'] as Array<any>).map(ShiftsIntervalFromJSON)),
        'participants': ((json['participants'] as Array<any>).map(ParticipantFromJSON)),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ShiftsResultFromJSON)),
    };
}

export function ShiftsToJSON(value?: Omit<Shifts, 'results'|'id'|'created_at'|'updated_at'|'private_id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseDrawToJSON(value),
        'intervals': ((value['intervals'] as Array<any>).map(ShiftsIntervalToJSON)),
        'participants': ((value['participants'] as Array<any>).map(ParticipantToJSON)),
    };
}

