/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseResult } from './BaseResult';
import {
    BaseResultFromJSON,
    BaseResultFromJSONTyped,
    BaseResultToJSON,
} from './BaseResult';
import type { ShiftsResultAllOfValue } from './ShiftsResultAllOfValue';
import {
    ShiftsResultAllOfValueFromJSON,
    ShiftsResultAllOfValueFromJSONTyped,
    ShiftsResultAllOfValueToJSON,
} from './ShiftsResultAllOfValue';

/**
 * 
 * @export
 * @interface ShiftsResult
 */
export interface ShiftsResult extends BaseResult {
    /**
     * 
     * @type {Array<ShiftsResultAllOfValue>}
     * @memberof ShiftsResult
     */
    value?: Array<ShiftsResultAllOfValue> | null;
}

/**
 * Check if a given object implements the ShiftsResult interface.
 */
export function instanceOfShiftsResult(value: object): value is ShiftsResult {
    return true;
}

export function ShiftsResultFromJSON(json: any): ShiftsResult {
    return ShiftsResultFromJSONTyped(json, false);
}

export function ShiftsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShiftsResult {
    if (json == null) {
        return json;
    }
    return {
        ...BaseResultFromJSONTyped(json, ignoreDiscriminator),
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(ShiftsResultAllOfValueFromJSON)),
    };
}

export function ShiftsResultToJSON(value?: Omit<ShiftsResult, 'id'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseResultToJSON(value),
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(ShiftsResultAllOfValueToJSON)),
    };
}

