/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionTier
 */
export interface SubscriptionTier {
    /**
     * Maximum number of Instagram comments allowed for this tier
     * @type {number}
     * @memberof SubscriptionTier
     */
    maxInstagramComments: number;
    /**
     * Display name of the subscription tier
     * @type {string}
     * @memberof SubscriptionTier
     */
    name: string;
}

/**
 * Check if a given object implements the SubscriptionTier interface.
 */
export function instanceOfSubscriptionTier(value: object): value is SubscriptionTier {
    if (!('maxInstagramComments' in value) || value['maxInstagramComments'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SubscriptionTierFromJSON(json: any): SubscriptionTier {
    return SubscriptionTierFromJSONTyped(json, false);
}

export function SubscriptionTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionTier {
    if (json == null) {
        return json;
    }
    return {
        
        'maxInstagramComments': json['max_instagram_comments'],
        'name': json['name'],
    };
}

export function SubscriptionTierToJSON(value?: SubscriptionTier | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'max_instagram_comments': value['maxInstagramComments'],
        'name': value['name'],
    };
}

