/* tslint:disable */
/* eslint-disable */
/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrawMetadata } from './DrawMetadata';
import {
    DrawMetadataFromJSON,
    DrawMetadataFromJSONTyped,
    DrawMetadataToJSON,
} from './DrawMetadata';
import type { BaseDraw } from './BaseDraw';
import {
    BaseDrawFromJSON,
    BaseDrawFromJSONTyped,
    BaseDrawToJSON,
} from './BaseDraw';
import type { Participant } from './Participant';
import {
    ParticipantFromJSON,
    ParticipantFromJSONTyped,
    ParticipantToJSON,
} from './Participant';
import type { TournamentResult } from './TournamentResult';
import {
    TournamentResultFromJSON,
    TournamentResultFromJSONTyped,
    TournamentResultToJSON,
} from './TournamentResult';

/**
 * 
 * @export
 * @interface Tournament
 */
export interface Tournament extends BaseDraw {
    /**
     * 
     * @type {Array<Participant>}
     * @memberof Tournament
     */
    participants: Array<Participant>;
    /**
     * 
     * @type {Array<TournamentResult>}
     * @memberof Tournament
     */
    readonly results?: Array<TournamentResult>;
}



/**
 * Check if a given object implements the Tournament interface.
 */
export function instanceOfTournament(value: object): value is Tournament {
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function TournamentFromJSON(json: any): Tournament {
    return TournamentFromJSONTyped(json, false);
}

export function TournamentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tournament {
    if (json == null) {
        return json;
    }
    return {
        ...BaseDrawFromJSONTyped(json, ignoreDiscriminator),
        'participants': ((json['participants'] as Array<any>).map(ParticipantFromJSON)),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TournamentResultFromJSON)),
    };
}

export function TournamentToJSON(value?: Omit<Tournament, 'results'|'id'|'created_at'|'updated_at'|'private_id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseDrawToJSON(value),
        'participants': ((value['participants'] as Array<any>).map(ParticipantToJSON)),
    };
}

