/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseObject', 'model/DrawMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseObject'), require('./DrawMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.EchaloasuerteJsSdk) {
      root.EchaloasuerteJsSdk = {};
    }
    root.EchaloasuerteJsSdk.BaseDraw = factory(root.EchaloasuerteJsSdk.ApiClient, root.EchaloasuerteJsSdk.BaseObject, root.EchaloasuerteJsSdk.DrawMetadata);
  }
}(this, function(ApiClient, BaseObject, DrawMetadata) {
  'use strict';




  /**
   * The BaseDraw model module.
   * @module model/BaseDraw
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>BaseDraw</code>.
   * @alias module:model/BaseDraw
   * @class
   * @extends module:model/BaseObject
   * @implements module:model/BaseObject
   */
  var exports = function() {
    var _this = this;
    BaseObject.call(_this);
    BaseObject.call(_this);





  };

  /**
   * Constructs a <code>BaseDraw</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseDraw} obj Optional instance to populate.
   * @return {module:model/BaseDraw} The populated <code>BaseDraw</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BaseObject.constructFromObject(data, obj);
      BaseObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('private_id')) {
        obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BaseObject.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} private_id
   */
  exports.prototype['private_id'] = undefined;
  /**
   * @member {Array.<module:model/DrawMetadata>} metadata
   */
  exports.prototype['metadata'] = undefined;

  // Implement BaseObject interface:
  /**
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {Date} created_at
   */
exports.prototype['created_at'] = undefined;



  return exports;
}));


