/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseDraw', 'model/CoinResult', 'model/DrawMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseDraw'), require('./CoinResult'), require('./DrawMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.EchaloasuerteJsSdk) {
      root.EchaloasuerteJsSdk = {};
    }
    root.EchaloasuerteJsSdk.Coin = factory(root.EchaloasuerteJsSdk.ApiClient, root.EchaloasuerteJsSdk.BaseDraw, root.EchaloasuerteJsSdk.CoinResult, root.EchaloasuerteJsSdk.DrawMetadata);
  }
}(this, function(ApiClient, BaseDraw, CoinResult, DrawMetadata) {
  'use strict';




  /**
   * The Coin model module.
   * @module model/Coin
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Coin</code>.
   * @alias module:model/Coin
   * @class
   * @extends module:model/BaseDraw
   * @implements module:model/BaseDraw
   */
  var exports = function() {
    var _this = this;
    BaseDraw.call(_this);
    BaseDraw.call(_this);

  };

  /**
   * Constructs a <code>Coin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Coin} obj Optional instance to populate.
   * @return {module:model/Coin} The populated <code>Coin</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BaseDraw.constructFromObject(data, obj);
      BaseDraw.constructFromObject(data, obj);
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [CoinResult]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BaseDraw.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/CoinResult>} results
   */
  exports.prototype['results'] = undefined;

  // Implement BaseDraw interface:
  /**
   * @member {} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {} updated_at
   */
exports.prototype['updated_at'] = undefined;

  /**
   * @member {} title
   */
exports.prototype['title'] = undefined;

  /**
   * @member {} description
   */
exports.prototype['description'] = undefined;

  /**
   * @member {} private_id
   */
exports.prototype['private_id'] = undefined;

  /**
   * @member {} metadata
   */
exports.prototype['metadata'] = undefined;



  return exports;
}));


