/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseFieldsCreate from './BaseFieldsCreate';
import DrawMetadata from './DrawMetadata';
import LotteryFields from './LotteryFields';
import ParticipantField from './ParticipantField';

/**
 * The CreateLotteryPayload model module.
 * @module model/CreateLotteryPayload
 * @version 1.0.0
 */
class CreateLotteryPayload {
    /**
     * Constructs a new <code>CreateLotteryPayload</code>.
     * @alias module:model/CreateLotteryPayload
     * @implements module:model/BaseFieldsCreate
     * @implements module:model/LotteryFields
     * @param participants {Array.<module:model/ParticipantField>} 
     */
    constructor(participants) { 
        BaseFieldsCreate.initialize(this);LotteryFields.initialize(this, participants);
        CreateLotteryPayload.initialize(this, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participants) { 
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>CreateLotteryPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLotteryPayload} obj Optional instance to populate.
     * @return {module:model/CreateLotteryPayload} The populated <code>CreateLotteryPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLotteryPayload();
            BaseFieldsCreate.constructFromObject(data, obj);
            LotteryFields.constructFromObject(data, obj);

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [ParticipantField]);
            }
            if (data.hasOwnProperty('number_of_results')) {
                obj['number_of_results'] = ApiClient.convertToType(data['number_of_results'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateLotteryPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateLotteryPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateLotteryPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['metadata']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['metadata'])) {
                throw new Error("Expected the field `metadata` to be an array in the JSON data but got " + data['metadata']);
            }
            // validate the optional field `metadata` (array)
            for (const item of data['metadata']) {
                DrawMetadata.validateJSON(item);
            };
        }
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                ParticipantField.validateJSON(item);
            };
        }

        return true;
    }


}

CreateLotteryPayload.RequiredProperties = ["participants"];

/**
 * @member {String} title
 */
CreateLotteryPayload.prototype['title'] = undefined;

/**
 * @member {String} description
 */
CreateLotteryPayload.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
CreateLotteryPayload.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
CreateLotteryPayload.prototype['participants'] = undefined;

/**
 * @member {Number} number_of_results
 * @default 1
 */
CreateLotteryPayload.prototype['number_of_results'] = 1;


// Implement BaseFieldsCreate interface:
/**
 * @member {String} title
 */
BaseFieldsCreate.prototype['title'] = undefined;
/**
 * @member {String} description
 */
BaseFieldsCreate.prototype['description'] = undefined;
/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
BaseFieldsCreate.prototype['metadata'] = undefined;
// Implement LotteryFields interface:
/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
LotteryFields.prototype['participants'] = undefined;
/**
 * @member {Number} number_of_results
 * @default 1
 */
LotteryFields.prototype['number_of_results'] = 1;




export default CreateLotteryPayload;

