/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DrawTossPayload model module.
 * @module model/DrawTossPayload
 * @version v1
 */
class DrawTossPayload {
    /**
     * Constructs a new <code>DrawTossPayload</code>.
     * @alias module:model/DrawTossPayload
     */
    constructor() { 
        
        DrawTossPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DrawTossPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DrawTossPayload} obj Optional instance to populate.
     * @return {module:model/DrawTossPayload} The populated <code>DrawTossPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DrawTossPayload();

            if (data.hasOwnProperty('schedule_date')) {
                obj['schedule_date'] = ApiClient.convertToType(data['schedule_date'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} schedule_date
 */
DrawTossPayload.prototype['schedule_date'] = undefined;






export default DrawTossPayload;

