/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseDraw from './BaseDraw';
import DrawMetadata from './DrawMetadata';
import GroupsAllOf from './GroupsAllOf';
import GroupsResult from './GroupsResult';
import Participant from './Participant';

/**
 * The Groups model module.
 * @module model/Groups
 * @version 0.0.1
 */
class Groups {
    /**
     * Constructs a new <code>Groups</code>.
     * @alias module:model/Groups
     * @implements module:model/BaseDraw
     * @implements module:model/GroupsAllOf
     * @param participants {Array.<module:model/Participant>} 
     * @param numberOfGroups {Number} 
     */
    constructor(participants, numberOfGroups) { 
        BaseDraw.initialize(this);GroupsAllOf.initialize(this, participants, numberOfGroups);
        Groups.initialize(this, participants, numberOfGroups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participants, numberOfGroups) { 
        obj['participants'] = participants;
        obj['number_of_groups'] = numberOfGroups;
    }

    /**
     * Constructs a <code>Groups</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Groups} obj Optional instance to populate.
     * @return {module:model/Groups} The populated <code>Groups</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Groups();
            BaseDraw.constructFromObject(data, obj);
            GroupsAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('private_id')) {
                obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
            }
            if (data.hasOwnProperty('number_of_groups')) {
                obj['number_of_groups'] = ApiClient.convertToType(data['number_of_groups'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [GroupsResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Groups.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Groups.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Groups.prototype['updated_at'] = undefined;

/**
 * @member {String} title
 */
Groups.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Groups.prototype['description'] = undefined;

/**
 * @member {String} private_id
 */
Groups.prototype['private_id'] = undefined;

/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
Groups.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/Participant>} participants
 */
Groups.prototype['participants'] = undefined;

/**
 * @member {Number} number_of_groups
 */
Groups.prototype['number_of_groups'] = undefined;

/**
 * @member {Array.<module:model/GroupsResult>} results
 */
Groups.prototype['results'] = undefined;


// Implement BaseDraw interface:
/**
 * @member {String} id
 */
BaseDraw.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseDraw.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseDraw.prototype['updated_at'] = undefined;
/**
 * @member {String} title
 */
BaseDraw.prototype['title'] = undefined;
/**
 * @member {String} description
 */
BaseDraw.prototype['description'] = undefined;
/**
 * @member {String} private_id
 */
BaseDraw.prototype['private_id'] = undefined;
/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
BaseDraw.prototype['metadata'] = undefined;
// Implement GroupsAllOf interface:
/**
 * @member {Array.<module:model/Participant>} participants
 */
GroupsAllOf.prototype['participants'] = undefined;
/**
 * @member {Number} number_of_groups
 */
GroupsAllOf.prototype['number_of_groups'] = undefined;
/**
 * @member {Array.<module:model/GroupsResult>} results
 */
GroupsAllOf.prototype['results'] = undefined;




export default Groups;

