/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupsResult from './GroupsResult';
import Participant from './Participant';

/**
 * The GroupsAllOf model module.
 * @module model/GroupsAllOf
 * @version 0.0.1
 */
class GroupsAllOf {
    /**
     * Constructs a new <code>GroupsAllOf</code>.
     * @alias module:model/GroupsAllOf
     * @param participants {Array.<module:model/Participant>} 
     * @param numberOfGroups {Number} 
     */
    constructor(participants, numberOfGroups) { 
        
        GroupsAllOf.initialize(this, participants, numberOfGroups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participants, numberOfGroups) { 
        obj['participants'] = participants;
        obj['number_of_groups'] = numberOfGroups;
    }

    /**
     * Constructs a <code>GroupsAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupsAllOf} obj Optional instance to populate.
     * @return {module:model/GroupsAllOf} The populated <code>GroupsAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupsAllOf();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
            }
            if (data.hasOwnProperty('number_of_groups')) {
                obj['number_of_groups'] = ApiClient.convertToType(data['number_of_groups'], 'Number');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [GroupsResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Participant>} participants
 */
GroupsAllOf.prototype['participants'] = undefined;

/**
 * @member {Number} number_of_groups
 */
GroupsAllOf.prototype['number_of_groups'] = undefined;

/**
 * @member {Array.<module:model/GroupsResult>} results
 */
GroupsAllOf.prototype['results'] = undefined;






export default GroupsAllOf;

