/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstagramPreviewResponse model module.
 * @module model/InstagramPreviewResponse
 * @version 0.0.1
 */
class InstagramPreviewResponse {
    /**
     * Constructs a new <code>InstagramPreviewResponse</code>.
     * @alias module:model/InstagramPreviewResponse
     */
    constructor() { 
        
        InstagramPreviewResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstagramPreviewResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstagramPreviewResponse} obj Optional instance to populate.
     * @return {module:model/InstagramPreviewResponse} The populated <code>InstagramPreviewResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstagramPreviewResponse();

            if (data.hasOwnProperty('thumbnail')) {
                obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
            }
            if (data.hasOwnProperty('likes')) {
                obj['likes'] = ApiClient.convertToType(data['likes'], 'Number');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} thumbnail
 */
InstagramPreviewResponse.prototype['thumbnail'] = undefined;

/**
 * @member {Number} likes
 */
InstagramPreviewResponse.prototype['likes'] = undefined;

/**
 * @member {Number} comments
 */
InstagramPreviewResponse.prototype['comments'] = undefined;






export default InstagramPreviewResponse;

