/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PrizeField from './PrizeField';

/**
 * The InstagramFields model module.
 * @module model/InstagramFields
 * @version 1.0.0
 */
class InstagramFields {
    /**
     * Constructs a new <code>InstagramFields</code>.
     * @alias module:model/InstagramFields
     * @param prizes {Array.<module:model/PrizeField>} 
     * @param useLikes {Boolean} 
     * @param minMentions {Number} 
     * @param postUrl {String} 
     */
    constructor(prizes, useLikes, minMentions, postUrl) { 
        
        InstagramFields.initialize(this, prizes, useLikes, minMentions, postUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, prizes, useLikes, minMentions, postUrl) { 
        obj['prizes'] = prizes;
        obj['use_likes'] = useLikes || false;
        obj['min_mentions'] = minMentions || 0;
        obj['post_url'] = postUrl;
    }

    /**
     * Constructs a <code>InstagramFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstagramFields} obj Optional instance to populate.
     * @return {module:model/InstagramFields} The populated <code>InstagramFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstagramFields();

            if (data.hasOwnProperty('prizes')) {
                obj['prizes'] = ApiClient.convertToType(data['prizes'], [PrizeField]);
            }
            if (data.hasOwnProperty('use_likes')) {
                obj['use_likes'] = ApiClient.convertToType(data['use_likes'], 'Boolean');
            }
            if (data.hasOwnProperty('min_mentions')) {
                obj['min_mentions'] = ApiClient.convertToType(data['min_mentions'], 'Number');
            }
            if (data.hasOwnProperty('post_url')) {
                obj['post_url'] = ApiClient.convertToType(data['post_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstagramFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstagramFields</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InstagramFields.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['prizes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prizes'])) {
                throw new Error("Expected the field `prizes` to be an array in the JSON data but got " + data['prizes']);
            }
            // validate the optional field `prizes` (array)
            for (const item of data['prizes']) {
                PrizeField.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['post_url'] && !(typeof data['post_url'] === 'string' || data['post_url'] instanceof String)) {
            throw new Error("Expected the field `post_url` to be a primitive type in the JSON string but got " + data['post_url']);
        }

        return true;
    }


}

InstagramFields.RequiredProperties = ["prizes", "use_likes", "min_mentions", "post_url"];

/**
 * @member {Array.<module:model/PrizeField>} prizes
 */
InstagramFields.prototype['prizes'] = undefined;

/**
 * @member {Boolean} use_likes
 * @default false
 */
InstagramFields.prototype['use_likes'] = false;

/**
 * @member {Number} min_mentions
 * @default 0
 */
InstagramFields.prototype['min_mentions'] = 0;

/**
 * @member {String} post_url
 */
InstagramFields.prototype['post_url'] = undefined;






export default InstagramFields;

