/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseDraw', 'model/DrawMetadata', 'model/LetterResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseDraw'), require('./DrawMetadata'), require('./LetterResult'));
  } else {
    // Browser globals (root is window)
    if (!root.EchaloasuerteJsSdk) {
      root.EchaloasuerteJsSdk = {};
    }
    root.EchaloasuerteJsSdk.Letter = factory(root.EchaloasuerteJsSdk.ApiClient, root.EchaloasuerteJsSdk.BaseDraw, root.EchaloasuerteJsSdk.DrawMetadata, root.EchaloasuerteJsSdk.LetterResult);
  }
}(this, function(ApiClient, BaseDraw, DrawMetadata, LetterResult) {
  'use strict';




  /**
   * The Letter model module.
   * @module model/Letter
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Letter</code>.
   * @alias module:model/Letter
   * @class
   * @extends module:model/BaseDraw
   * @implements module:model/BaseDraw
   */
  var exports = function() {
    var _this = this;
    BaseDraw.call(_this);
    BaseDraw.call(_this);



  };

  /**
   * Constructs a <code>Letter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Letter} obj Optional instance to populate.
   * @return {module:model/Letter} The populated <code>Letter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BaseDraw.constructFromObject(data, obj);
      BaseDraw.constructFromObject(data, obj);
      if (data.hasOwnProperty('number_of_results')) {
        obj['number_of_results'] = ApiClient.convertToType(data['number_of_results'], 'Number');
      }
      if (data.hasOwnProperty('allow_repeated_results')) {
        obj['allow_repeated_results'] = ApiClient.convertToType(data['allow_repeated_results'], 'Boolean');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [LetterResult]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BaseDraw.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Number} number_of_results
   * @default 1
   */
  exports.prototype['number_of_results'] = 1;
  /**
   * @member {Boolean} allow_repeated_results
   * @default true
   */
  exports.prototype['allow_repeated_results'] = true;
  /**
   * @member {Array.<module:model/LetterResult>} results
   */
  exports.prototype['results'] = undefined;

  // Implement BaseDraw interface:
  /**
   * @member {} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {} updated_at
   */
exports.prototype['updated_at'] = undefined;

  /**
   * @member {} title
   */
exports.prototype['title'] = undefined;

  /**
   * @member {} description
   */
exports.prototype['description'] = undefined;

  /**
   * @member {} private_id
   */
exports.prototype['private_id'] = undefined;

  /**
   * @member {} metadata
   */
exports.prototype['metadata'] = undefined;



  return exports;
}));


