/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseDraw', 'model/DrawMetadata', 'model/LotteryResult', 'model/Participant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseDraw'), require('./DrawMetadata'), require('./LotteryResult'), require('./Participant'));
  } else {
    // Browser globals (root is window)
    if (!root.EchaloasuerteJsSdk) {
      root.EchaloasuerteJsSdk = {};
    }
    root.EchaloasuerteJsSdk.Lottery = factory(root.EchaloasuerteJsSdk.ApiClient, root.EchaloasuerteJsSdk.BaseDraw, root.EchaloasuerteJsSdk.DrawMetadata, root.EchaloasuerteJsSdk.LotteryResult, root.EchaloasuerteJsSdk.Participant);
  }
}(this, function(ApiClient, BaseDraw, DrawMetadata, LotteryResult, Participant) {
  'use strict';




  /**
   * The Lottery model module.
   * @module model/Lottery
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Lottery</code>.
   * @alias module:model/Lottery
   * @class
   * @extends module:model/BaseDraw
   * @implements module:model/BaseDraw
   * @param participants {} 
   */
  var exports = function(participants) {
    var _this = this;
    BaseDraw.call(_this);
    BaseDraw.call(_this);
    _this['participants'] = participants;

  };

  /**
   * Constructs a <code>Lottery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lottery} obj Optional instance to populate.
   * @return {module:model/Lottery} The populated <code>Lottery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BaseDraw.constructFromObject(data, obj);
      BaseDraw.constructFromObject(data, obj);
      if (data.hasOwnProperty('participants')) {
        obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [LotteryResult]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BaseDraw.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/Participant>} participants
   */
  exports.prototype['participants'] = undefined;
  /**
   * @member {Array.<module:model/LotteryResult>} results
   */
  exports.prototype['results'] = undefined;

  // Implement BaseDraw interface:
  /**
   * @member {} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {} updated_at
   */
exports.prototype['updated_at'] = undefined;

  /**
   * @member {} title
   */
exports.prototype['title'] = undefined;

  /**
   * @member {} description
   */
exports.prototype['description'] = undefined;

  /**
   * @member {} private_id
   */
exports.prototype['private_id'] = undefined;

  /**
   * @member {} metadata
   */
exports.prototype['metadata'] = undefined;



  return exports;
}));


