/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParticipantField from './ParticipantField';

/**
 * The LotteryFields model module.
 * @module model/LotteryFields
 * @version 1.0.0
 */
class LotteryFields {
    /**
     * Constructs a new <code>LotteryFields</code>.
     * @alias module:model/LotteryFields
     * @param participants {Array.<module:model/ParticipantField>} 
     */
    constructor(participants) { 
        
        LotteryFields.initialize(this, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, participants) { 
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>LotteryFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LotteryFields} obj Optional instance to populate.
     * @return {module:model/LotteryFields} The populated <code>LotteryFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LotteryFields();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [ParticipantField]);
            }
            if (data.hasOwnProperty('number_of_results')) {
                obj['number_of_results'] = ApiClient.convertToType(data['number_of_results'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LotteryFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LotteryFields</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LotteryFields.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                ParticipantField.validateJSON(item);
            };
        }

        return true;
    }


}

LotteryFields.RequiredProperties = ["participants"];

/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
LotteryFields.prototype['participants'] = undefined;

/**
 * @member {Number} number_of_results
 * @default 1
 */
LotteryFields.prototype['number_of_results'] = 1;






export default LotteryFields;

