/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseObject from './BaseObject';

/**
 * The Participant model module.
 * @module model/Participant
 * @version v1
 */
class Participant {
    /**
     * Constructs a new <code>Participant</code>.
     * @alias module:model/Participant
     * @extends module:model/BaseObject
     * @implements module:model/BaseObject
     * @param name {} 
     */
    constructor(name) { 
        BaseObject.initialize(this);
        Participant.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Participant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Participant} obj Optional instance to populate.
     * @return {module:model/Participant} The populated <code>Participant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Participant();
            BaseObject.constructFromObject(data, obj);
            BaseObject.constructFromObject(data, obj);

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('facebook_id')) {
                obj['facebook_id'] = ApiClient.convertToType(data['facebook_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Participant.prototype['name'] = undefined;

/**
 * @member {String} facebook_id
 */
Participant.prototype['facebook_id'] = undefined;


// Implement BaseObject interface:
/**
 * @member {String} id
 */
BaseObject.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseObject.prototype['created_at'] = undefined;




export default Participant;

