/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaypalCreatePayload model module.
 * @module model/PaypalCreatePayload
 * @version 1.0.0
 */
class PaypalCreatePayload {
    /**
     * Constructs a new <code>PaypalCreatePayload</code>.
     * @alias module:model/PaypalCreatePayload
     * @param options {Array.<module:model/PaypalCreatePayload.OptionsEnum>} 
     * @param drawUrl {String} 
     * @param drawId {String} 
     */
    constructor(options, drawUrl, drawId) { 
        
        PaypalCreatePayload.initialize(this, options, drawUrl, drawId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, options, drawUrl, drawId) { 
        obj['options'] = options;
        obj['draw_url'] = drawUrl;
        obj['draw_id'] = drawId;
    }

    /**
     * Constructs a <code>PaypalCreatePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaypalCreatePayload} obj Optional instance to populate.
     * @return {module:model/PaypalCreatePayload} The populated <code>PaypalCreatePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaypalCreatePayload();

            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], ['String']);
            }
            if (data.hasOwnProperty('draw_url')) {
                obj['draw_url'] = ApiClient.convertToType(data['draw_url'], 'String');
            }
            if (data.hasOwnProperty('draw_id')) {
                obj['draw_id'] = ApiClient.convertToType(data['draw_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaypalCreatePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaypalCreatePayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaypalCreatePayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['options'])) {
            throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
        }
        // ensure the json data is a string
        if (data['draw_url'] && !(typeof data['draw_url'] === 'string' || data['draw_url'] instanceof String)) {
            throw new Error("Expected the field `draw_url` to be a primitive type in the JSON string but got " + data['draw_url']);
        }
        // ensure the json data is a string
        if (data['draw_id'] && !(typeof data['draw_id'] === 'string' || data['draw_id'] instanceof String)) {
            throw new Error("Expected the field `draw_id` to be a primitive type in the JSON string but got " + data['draw_id']);
        }

        return true;
    }


}

PaypalCreatePayload.RequiredProperties = ["options", "draw_url", "draw_id"];

/**
 * @member {Array.<module:model/PaypalCreatePayload.OptionsEnum>} options
 */
PaypalCreatePayload.prototype['options'] = undefined;

/**
 * @member {String} draw_url
 */
PaypalCreatePayload.prototype['draw_url'] = undefined;

/**
 * @member {String} draw_id
 */
PaypalCreatePayload.prototype['draw_id'] = undefined;





/**
 * Allowed values for the <code>options</code> property.
 * @enum {String}
 * @readonly
 */
PaypalCreatePayload['OptionsEnum'] = {

    /**
     * value: "CERTIFIED"
     * @const
     */
    "CERTIFIED": "CERTIFIED",

    /**
     * value: "ADFREE"
     * @const
     */
    "ADFREE": "ADFREE",

    /**
     * value: "SUPPORT"
     * @const
     */
    "SUPPORT": "SUPPORT"
};



export default PaypalCreatePayload;

