/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParticipantField from './ParticipantField';
import PrizeField from './PrizeField';

/**
 * The RaffleFields model module.
 * @module model/RaffleFields
 * @version 1.0.0
 */
class RaffleFields {
    /**
     * Constructs a new <code>RaffleFields</code>.
     * @alias module:model/RaffleFields
     * @param prizes {Array.<module:model/PrizeField>} 
     * @param participants {Array.<module:model/ParticipantField>} 
     */
    constructor(prizes, participants) { 
        
        RaffleFields.initialize(this, prizes, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, prizes, participants) { 
        obj['prizes'] = prizes;
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>RaffleFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RaffleFields} obj Optional instance to populate.
     * @return {module:model/RaffleFields} The populated <code>RaffleFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RaffleFields();

            if (data.hasOwnProperty('prizes')) {
                obj['prizes'] = ApiClient.convertToType(data['prizes'], [PrizeField]);
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [ParticipantField]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RaffleFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RaffleFields</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RaffleFields.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['prizes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prizes'])) {
                throw new Error("Expected the field `prizes` to be an array in the JSON data but got " + data['prizes']);
            }
            // validate the optional field `prizes` (array)
            for (const item of data['prizes']) {
                PrizeField.validateJSON(item);
            };
        }
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                ParticipantField.validateJSON(item);
            };
        }

        return true;
    }


}

RaffleFields.RequiredProperties = ["prizes", "participants"];

/**
 * @member {Array.<module:model/PrizeField>} prizes
 */
RaffleFields.prototype['prizes'] = undefined;

/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
RaffleFields.prototype['participants'] = undefined;






export default RaffleFields;

