/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RandomNumberResult from './RandomNumberResult';

/**
 * The RandomNumberAllOf model module.
 * @module model/RandomNumberAllOf
 * @version 0.0.1
 */
class RandomNumberAllOf {
    /**
     * Constructs a new <code>RandomNumberAllOf</code>.
     * @alias module:model/RandomNumberAllOf
     * @param rangeMin {Number} 
     * @param rangeMax {Number} 
     */
    constructor(rangeMin, rangeMax) { 
        
        RandomNumberAllOf.initialize(this, rangeMin, rangeMax);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rangeMin, rangeMax) { 
        obj['range_min'] = rangeMin;
        obj['range_max'] = rangeMax;
    }

    /**
     * Constructs a <code>RandomNumberAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RandomNumberAllOf} obj Optional instance to populate.
     * @return {module:model/RandomNumberAllOf} The populated <code>RandomNumberAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RandomNumberAllOf();

            if (data.hasOwnProperty('range_min')) {
                obj['range_min'] = ApiClient.convertToType(data['range_min'], 'Number');
            }
            if (data.hasOwnProperty('range_max')) {
                obj['range_max'] = ApiClient.convertToType(data['range_max'], 'Number');
            }
            if (data.hasOwnProperty('number_of_results')) {
                obj['number_of_results'] = ApiClient.convertToType(data['number_of_results'], 'Number');
            }
            if (data.hasOwnProperty('allow_repeated_results')) {
                obj['allow_repeated_results'] = ApiClient.convertToType(data['allow_repeated_results'], 'Boolean');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [RandomNumberResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} range_min
 */
RandomNumberAllOf.prototype['range_min'] = undefined;

/**
 * @member {Number} range_max
 */
RandomNumberAllOf.prototype['range_max'] = undefined;

/**
 * @member {Number} number_of_results
 * @default 1
 */
RandomNumberAllOf.prototype['number_of_results'] = 1;

/**
 * @member {Boolean} allow_repeated_results
 * @default true
 */
RandomNumberAllOf.prototype['allow_repeated_results'] = true;

/**
 * @member {Array.<module:model/RandomNumberResult>} results
 */
RandomNumberAllOf.prototype['results'] = undefined;






export default RandomNumberAllOf;

