/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecretSantaResult model module.
 * @module model/SecretSantaResult
 * @version 0.0.1
 */
class SecretSantaResult {
    /**
     * Constructs a new <code>SecretSantaResult</code>.
     * @alias module:model/SecretSantaResult
     */
    constructor() { 
        
        SecretSantaResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecretSantaResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecretSantaResult} obj Optional instance to populate.
     * @return {module:model/SecretSantaResult} The populated <code>SecretSantaResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretSantaResult();

            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} source
 */
SecretSantaResult.prototype['source'] = undefined;

/**
 * @member {String} target
 */
SecretSantaResult.prototype['target'] = undefined;






export default SecretSantaResult;

