/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SecretSantaErrorResponseBody from './SecretSantaErrorResponseBody';

/**
 * The SecretSantaErrorResponse model module.
 * @module model/SecretSantaErrorResponse
 * @version 1.0.0
 */
class SecretSantaErrorResponse {
    /**
     * Constructs a new <code>SecretSantaErrorResponse</code>.
     * @alias module:model/SecretSantaErrorResponse
     */
    constructor() { 
        
        SecretSantaErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecretSantaErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecretSantaErrorResponse} obj Optional instance to populate.
     * @return {module:model/SecretSantaErrorResponse} The populated <code>SecretSantaErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretSantaErrorResponse();

            if (data.hasOwnProperty('body')) {
                obj['body'] = SecretSantaErrorResponseBody.constructFromObject(data['body']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecretSantaErrorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecretSantaErrorResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `body`
        if (data['body']) { // data not null
          SecretSantaErrorResponseBody.validateJSON(data['body']);
        }

        return true;
    }


}



/**
 * @member {module:model/SecretSantaErrorResponseBody} body
 */
SecretSantaErrorResponse.prototype['body'] = undefined;






export default SecretSantaErrorResponse;

