/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecretSantaParticipants model module.
 * @module model/SecretSantaParticipants
 * @version 0.0.1
 */
class SecretSantaParticipants {
    /**
     * Constructs a new <code>SecretSantaParticipants</code>.
     * @alias module:model/SecretSantaParticipants
     */
    constructor() { 
        
        SecretSantaParticipants.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecretSantaParticipants</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecretSantaParticipants} obj Optional instance to populate.
     * @return {module:model/SecretSantaParticipants} The populated <code>SecretSantaParticipants</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretSantaParticipants();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('exclusions')) {
                obj['exclusions'] = ApiClient.convertToType(data['exclusions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SecretSantaParticipants.prototype['name'] = undefined;

/**
 * @member {String} email
 */
SecretSantaParticipants.prototype['email'] = undefined;

/**
 * @member {Array.<String>} exclusions
 */
SecretSantaParticipants.prototype['exclusions'] = undefined;






export default SecretSantaParticipants;

