/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResult from './BaseResult';
import ShiftsResultAllOf from './ShiftsResultAllOf';
import ShiftsResultAllOfValue from './ShiftsResultAllOfValue';

/**
 * The ShiftsResult model module.
 * @module model/ShiftsResult
 * @version 0.0.1
 */
class ShiftsResult {
    /**
     * Constructs a new <code>ShiftsResult</code>.
     * @alias module:model/ShiftsResult
     * @implements module:model/BaseResult
     * @implements module:model/ShiftsResultAllOf
     */
    constructor() { 
        BaseResult.initialize(this);ShiftsResultAllOf.initialize(this);
        ShiftsResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShiftsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShiftsResult} obj Optional instance to populate.
     * @return {module:model/ShiftsResult} The populated <code>ShiftsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShiftsResult();
            BaseResult.constructFromObject(data, obj);
            ShiftsResultAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('schedule_date')) {
                obj['schedule_date'] = ApiClient.convertToType(data['schedule_date'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [ShiftsResultAllOfValue]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ShiftsResult.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
ShiftsResult.prototype['created_at'] = undefined;

/**
 * @member {Date} schedule_date
 */
ShiftsResult.prototype['schedule_date'] = undefined;

/**
 * @member {Array.<module:model/ShiftsResultAllOfValue>} value
 */
ShiftsResult.prototype['value'] = undefined;


// Implement BaseResult interface:
/**
 * @member {String} id
 */
BaseResult.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseResult.prototype['created_at'] = undefined;
/**
 * @member {Date} schedule_date
 */
BaseResult.prototype['schedule_date'] = undefined;
// Implement ShiftsResultAllOf interface:
/**
 * @member {Array.<module:model/ShiftsResultAllOfValue>} value
 */
ShiftsResultAllOf.prototype['value'] = undefined;




export default ShiftsResult;

