/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShiftsAllOfIntervals model module.
 * @module model/ShiftsAllOfIntervals
 * @version 0.0.1
 */
class ShiftsAllOfIntervals {
    /**
     * Constructs a new <code>ShiftsAllOfIntervals</code>.
     * @alias module:model/ShiftsAllOfIntervals
     * @param startTime {Date} 
     * @param endTime {Date} 
     */
    constructor(startTime, endTime) { 
        
        ShiftsAllOfIntervals.initialize(this, startTime, endTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startTime, endTime) { 
        obj['start_time'] = startTime;
        obj['end_time'] = endTime;
    }

    /**
     * Constructs a <code>ShiftsAllOfIntervals</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShiftsAllOfIntervals} obj Optional instance to populate.
     * @return {module:model/ShiftsAllOfIntervals} The populated <code>ShiftsAllOfIntervals</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShiftsAllOfIntervals();

            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} start_time
 */
ShiftsAllOfIntervals.prototype['start_time'] = undefined;

/**
 * @member {Date} end_time
 */
ShiftsAllOfIntervals.prototype['end_time'] = undefined;






export default ShiftsAllOfIntervals;

