/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Participant from './Participant';
import ShiftsAllOfIntervals from './ShiftsAllOfIntervals';
import ShiftsResult from './ShiftsResult';

/**
 * The ShiftsAllOf model module.
 * @module model/ShiftsAllOf
 * @version 0.0.1
 */
class ShiftsAllOf {
    /**
     * Constructs a new <code>ShiftsAllOf</code>.
     * @alias module:model/ShiftsAllOf
     * @param intervals {Array.<module:model/ShiftsAllOfIntervals>} 
     * @param participants {Array.<module:model/Participant>} 
     */
    constructor(intervals, participants) { 
        
        ShiftsAllOf.initialize(this, intervals, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, intervals, participants) { 
        obj['intervals'] = intervals;
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>ShiftsAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShiftsAllOf} obj Optional instance to populate.
     * @return {module:model/ShiftsAllOf} The populated <code>ShiftsAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShiftsAllOf();

            if (data.hasOwnProperty('intervals')) {
                obj['intervals'] = ApiClient.convertToType(data['intervals'], [ShiftsAllOfIntervals]);
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [ShiftsResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ShiftsAllOfIntervals>} intervals
 */
ShiftsAllOf.prototype['intervals'] = undefined;

/**
 * @member {Array.<module:model/Participant>} participants
 */
ShiftsAllOf.prototype['participants'] = undefined;

/**
 * @member {Array.<module:model/ShiftsResult>} results
 */
ShiftsAllOf.prototype['results'] = undefined;






export default ShiftsAllOf;

