/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResult from './BaseResult';

/**
 * The SpinnerResult model module.
 * @module model/SpinnerResult
 * @version 1.0.0
 */
class SpinnerResult {
    /**
     * Constructs a new <code>SpinnerResult</code>.
     * @alias module:model/SpinnerResult
     * @implements module:model/BaseResult
     */
    constructor() { 
        BaseResult.initialize(this);
        SpinnerResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SpinnerResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpinnerResult} obj Optional instance to populate.
     * @return {module:model/SpinnerResult} The populated <code>SpinnerResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpinnerResult();
            BaseResult.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('schedule_date')) {
                obj['schedule_date'] = ApiClient.convertToType(data['schedule_date'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpinnerResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpinnerResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
SpinnerResult.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
SpinnerResult.prototype['created_at'] = undefined;

/**
 * @member {Date} schedule_date
 */
SpinnerResult.prototype['schedule_date'] = undefined;

/**
 * @member {Number} value
 */
SpinnerResult.prototype['value'] = undefined;


// Implement BaseResult interface:
/**
 * @member {String} id
 */
BaseResult.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseResult.prototype['created_at'] = undefined;
/**
 * @member {Date} schedule_date
 */
BaseResult.prototype['schedule_date'] = undefined;




export default SpinnerResult;

