/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseDraw from './BaseDraw';
import DrawMetadata from './DrawMetadata';
import SpinnerAllOf from './SpinnerAllOf';
import SpinnerResult from './SpinnerResult';

/**
 * The Spinner model module.
 * @module model/Spinner
 * @version 0.0.1
 */
class Spinner {
    /**
     * Constructs a new <code>Spinner</code>.
     * @alias module:model/Spinner
     * @implements module:model/BaseDraw
     * @implements module:model/SpinnerAllOf
     */
    constructor() { 
        BaseDraw.initialize(this);SpinnerAllOf.initialize(this);
        Spinner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Spinner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Spinner} obj Optional instance to populate.
     * @return {module:model/Spinner} The populated <code>Spinner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Spinner();
            BaseDraw.constructFromObject(data, obj);
            SpinnerAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('private_id')) {
                obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], ['String']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [SpinnerResult]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Spinner.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Spinner.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Spinner.prototype['updated_at'] = undefined;

/**
 * @member {String} title
 */
Spinner.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Spinner.prototype['description'] = undefined;

/**
 * @member {String} private_id
 */
Spinner.prototype['private_id'] = undefined;

/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
Spinner.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/Spinner.PaymentsEnum>} payments
 */
Spinner.prototype['payments'] = undefined;

/**
 * @member {Array.<module:model/SpinnerResult>} results
 */
Spinner.prototype['results'] = undefined;


// Implement BaseDraw interface:
/**
 * @member {String} id
 */
BaseDraw.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseDraw.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseDraw.prototype['updated_at'] = undefined;
/**
 * @member {String} title
 */
BaseDraw.prototype['title'] = undefined;
/**
 * @member {String} description
 */
BaseDraw.prototype['description'] = undefined;
/**
 * @member {String} private_id
 */
BaseDraw.prototype['private_id'] = undefined;
/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
BaseDraw.prototype['metadata'] = undefined;
/**
 * @member {Array.<module:model/BaseDraw.PaymentsEnum>} payments
 */
BaseDraw.prototype['payments'] = undefined;
// Implement SpinnerAllOf interface:
/**
 * @member {Array.<module:model/SpinnerResult>} results
 */
SpinnerAllOf.prototype['results'] = undefined;



/**
 * Allowed values for the <code>payments</code> property.
 * @enum {String}
 * @readonly
 */
Spinner['PaymentsEnum'] = {

    /**
     * value: "CERTIFIED"
     * @const
     */
    "CERTIFIED": "CERTIFIED",

    /**
     * value: "ADFREE"
     * @const
     */
    "ADFREE": "ADFREE",

    /**
     * value: "SUPPORT"
     * @const
     */
    "SUPPORT": "SUPPORT"
};



export default Spinner;

