/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseDraw from './BaseDraw';
import DrawMetadata from './DrawMetadata';
import ParticipantField from './ParticipantField';
import TournamentFields from './TournamentFields';
import TournamentResult from './TournamentResult';

/**
 * The Tournament model module.
 * @module model/Tournament
 * @version 1.0.0
 */
class Tournament {
    /**
     * Constructs a new <code>Tournament</code>.
     * @alias module:model/Tournament
     * @implements module:model/BaseDraw
     * @implements module:model/TournamentFields
     * @param id {String} 
     * @param createdAt {Date} 
     * @param title {String} 
     * @param description {String} 
     * @param payments {Array.<module:model/Tournament.PaymentsEnum>} 
     * @param participants {Array.<module:model/ParticipantField>} 
     * @param results {Array.<module:model/TournamentResult>} 
     */
    constructor(id, createdAt, title, description, payments, participants, results) { 
        BaseDraw.initialize(this, id, createdAt, title, description, payments);TournamentFields.initialize(this, participants);
        Tournament.initialize(this, id, createdAt, title, description, payments, participants, results);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, title, description, payments, participants, results) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['title'] = title;
        obj['description'] = description;
        obj['payments'] = payments;
        obj['participants'] = participants;
        obj['results'] = results;
    }

    /**
     * Constructs a <code>Tournament</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tournament} obj Optional instance to populate.
     * @return {module:model/Tournament} The populated <code>Tournament</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tournament();
            BaseDraw.constructFromObject(data, obj);
            TournamentFields.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [DrawMetadata]);
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], ['String']);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('private_id')) {
                obj['private_id'] = ApiClient.convertToType(data['private_id'], 'String');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [ParticipantField]);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [TournamentResult]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Tournament</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Tournament</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Tournament.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['metadata']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['metadata'])) {
                throw new Error("Expected the field `metadata` to be an array in the JSON data but got " + data['metadata']);
            }
            // validate the optional field `metadata` (array)
            for (const item of data['metadata']) {
                DrawMetadata.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['payments'])) {
            throw new Error("Expected the field `payments` to be an array in the JSON data but got " + data['payments']);
        }
        // ensure the json data is a string
        if (data['private_id'] && !(typeof data['private_id'] === 'string' || data['private_id'] instanceof String)) {
            throw new Error("Expected the field `private_id` to be a primitive type in the JSON string but got " + data['private_id']);
        }
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                ParticipantField.validateJSON(item);
            };
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                TournamentResult.validateJSON(item);
            };
        }

        return true;
    }


}

Tournament.RequiredProperties = ["id", "created_at", "title", "description", "payments", "participants", "results"];

/**
 * @member {String} id
 */
Tournament.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Tournament.prototype['created_at'] = undefined;

/**
 * @member {String} title
 */
Tournament.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Tournament.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
Tournament.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/Tournament.PaymentsEnum>} payments
 */
Tournament.prototype['payments'] = undefined;

/**
 * @member {Date} updated_at
 */
Tournament.prototype['updated_at'] = undefined;

/**
 * @member {String} private_id
 */
Tournament.prototype['private_id'] = undefined;

/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
Tournament.prototype['participants'] = undefined;

/**
 * @member {Array.<module:model/TournamentResult>} results
 */
Tournament.prototype['results'] = undefined;


// Implement BaseDraw interface:
/**
 * @member {String} id
 */
BaseDraw.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseDraw.prototype['created_at'] = undefined;
/**
 * @member {String} title
 */
BaseDraw.prototype['title'] = undefined;
/**
 * @member {String} description
 */
BaseDraw.prototype['description'] = undefined;
/**
 * @member {Array.<module:model/DrawMetadata>} metadata
 */
BaseDraw.prototype['metadata'] = undefined;
/**
 * @member {Array.<module:model/BaseDraw.PaymentsEnum>} payments
 */
BaseDraw.prototype['payments'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseDraw.prototype['updated_at'] = undefined;
/**
 * @member {String} private_id
 */
BaseDraw.prototype['private_id'] = undefined;
// Implement TournamentFields interface:
/**
 * @member {Array.<module:model/ParticipantField>} participants
 */
TournamentFields.prototype['participants'] = undefined;



/**
 * Allowed values for the <code>payments</code> property.
 * @enum {String}
 * @readonly
 */
Tournament['PaymentsEnum'] = {

    /**
     * value: "CERTIFIED"
     * @const
     */
    "CERTIFIED": "CERTIFIED",

    /**
     * value: "ADFREE"
     * @const
     */
    "ADFREE": "ADFREE",

    /**
     * value: "SUPPORT"
     * @const
     */
    "SUPPORT": "SUPPORT"
};



export default Tournament;

