/**
 * EAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Participant from './Participant';

/**
 * The TournamentResultAllOfValue model module.
 * @module model/TournamentResultAllOfValue
 * @version 1.0.0
 */
class TournamentResultAllOfValue {
    /**
     * Constructs a new <code>TournamentResultAllOfValue</code>.
     * @alias module:model/TournamentResultAllOfValue
     */
    constructor() { 
        
        TournamentResultAllOfValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TournamentResultAllOfValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournamentResultAllOfValue} obj Optional instance to populate.
     * @return {module:model/TournamentResultAllOfValue} The populated <code>TournamentResultAllOfValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournamentResultAllOfValue();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [Participant]);
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'String');
            }
            if (data.hasOwnProperty('winner_id')) {
                obj['winner_id'] = ApiClient.convertToType(data['winner_id'], 'String');
            }
            if (data.hasOwnProperty('next_match_id')) {
                obj['next_match_id'] = ApiClient.convertToType(data['next_match_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournamentResultAllOfValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournamentResultAllOfValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                Participant.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['score'] && !(typeof data['score'] === 'string' || data['score'] instanceof String)) {
            throw new Error("Expected the field `score` to be a primitive type in the JSON string but got " + data['score']);
        }
        // ensure the json data is a string
        if (data['winner_id'] && !(typeof data['winner_id'] === 'string' || data['winner_id'] instanceof String)) {
            throw new Error("Expected the field `winner_id` to be a primitive type in the JSON string but got " + data['winner_id']);
        }
        // ensure the json data is a string
        if (data['next_match_id'] && !(typeof data['next_match_id'] === 'string' || data['next_match_id'] instanceof String)) {
            throw new Error("Expected the field `next_match_id` to be a primitive type in the JSON string but got " + data['next_match_id']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
TournamentResultAllOfValue.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/Participant>} participants
 */
TournamentResultAllOfValue.prototype['participants'] = undefined;

/**
 * @member {String} score
 */
TournamentResultAllOfValue.prototype['score'] = undefined;

/**
 * @member {String} winner_id
 */
TournamentResultAllOfValue.prototype['winner_id'] = undefined;

/**
 * @member {String} next_match_id
 */
TournamentResultAllOfValue.prototype['next_match_id'] = undefined;






export default TournamentResultAllOfValue;

