name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd sdk && npm version ${GITHUB_REF:10}
      - run: cd sdk && npm ci
      - run: cd sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
